version: "3"
services:
  api:
    build:
      context: api/
    volumes:
      - "./json:/usr/share/doc/"

  nginx:
    build:
      context: nginx/
    depends_on:
      - api
    ports:
      - "8000:80"

